In [3]:
import pandas as pd
from rapidfuzz import process, distance

BPS_CSV  = "BPS_Rappocini_clean.csv"
MAPS_CSV = "Scraping_Rappocini_clean.csv"

OUT_JW_CSV  = "MATCHING_Rappocini_JW.csv"
OUT_LEV_CSV = "MATCHING_Rappocini_LEV.csv"

df_bps  = pd.read_csv(BPS_CSV)
df_maps = pd.read_csv(MAPS_CSV)

# Pastikan tidak ada NaN
df_bps["Nama Usaha"] = df_bps["Nama Usaha"].fillna("").astype(str)
df_maps["title"]     = df_maps["title"].fillna("").astype(str)

# List nama usaha BPS
bps_names = df_bps["Nama Usaha"].tolist()

results_jw = []
results_lev = []

# PROSES MATCHING
for _, row in df_maps.iterrows():
    query_name = row["title"]

    if query_name.strip() == "":
        continue

    # MATCHING JARO-WINKLER
    best_jw = process.extractOne(
        query_name,
        bps_names,
        scorer=distance.JaroWinkler.normalized_similarity
    )

    nama_bps_jw, score_jw, idx_jw = best_jw
    bps_row_jw = df_bps.iloc[idx_jw]

    results_jw.append({
        "input_id": row.get("input_id", ""),
        "title_maps": query_name,
        "address_maps": row.get("address", ""),

        "IDSBR_best": bps_row_jw.get("IDSBR", ""),
        "nama_bps_best": nama_bps_jw,
        "alamat_bps_best": bps_row_jw.get("Alamat", ""),

        "score_jw": round(score_jw, 42)
    })

    # MATCHING LEVENSHTEIN
    best_lev = process.extractOne(
        query_name,
        bps_names,
        scorer=distance.Levenshtein.normalized_similarity
    )

    nama_bps_lev, score_lev, idx_lev = best_lev
    bps_row_lev = df_bps.iloc[idx_lev]

    results_lev.append({
        "input_id": row.get("input_id", ""),
        "title_maps": query_name,
        "address_maps": row.get("address", ""),

        "IDSBR_best": bps_row_lev.get("IDSBR", ""),
        "nama_bps_best": nama_bps_lev,
        "alamat_bps_best": bps_row_lev.get("Alamat", ""),

        "score_lev": round(score_lev, 2)
    })

df_result_jw = pd.DataFrame(results_jw)
df_result_lev = pd.DataFrame(results_lev)

df_result_jw.to_csv(OUT_JW_CSV, index=False)
df_result_lev.to_csv(OUT_LEV_CSV, index=False)

print("Selesai!")
print("File Jaro-Winkler :", OUT_JW_CSV)
print("File Levenshtein  :", OUT_LEV_CSV)

print("\nContoh hasil Jaro-Winkler:")
print(df_result_jw.head(10))

print("\nContoh hasil Levenshtein:")
print(df_result_lev.head(10))

Selesai!
File Jaro-Winkler : MATCHING_Rappocini_JW.csv
File Levenshtein  : MATCHING_Rappocini_LEV.csv

Contoh hasil Jaro-Winkler:
                               input_id                          title_maps  \
0  a1b862b7-f3dd-4080-8d73-191b75975673                    simetri cafe mks
1  9f9df669-eaf0-4928-a13f-cddf4346d781         agen xamthone plus makassar
2  a1b862b7-f3dd-4080-8d73-191b75975673              daun coffee monginsidi
3  a3f39cd3-b9af-4647-a544-aeb050afa744                paprik"perfume shop"
4  a3f39cd3-b9af-4647-a544-aeb050afa744                          iye parfum
5  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f  homecare dan sunat modern makassar
6  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f                  klinik alvaro care
7  a3f39cd3-b9af-4647-a544-aeb050afa744                       aa bar parfum
8  a3f39cd3-b9af-4647-a544-aeb050afa744                   dirah shop parfum
9  a3f39cd3-b9af-4647-a544-aeb050afa744         berlian parfume jipang raya

                                        address_maps  IDSBR_best  \
0  Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...     4471585
1  JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...     3532554
2  komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...     3365337
3  Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...     3560125
4  RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...     4026968
5  Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...     4325925
6  Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...    97502853
7  Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...     3844982
8  RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...     3814015
9  Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...     3452839

            nama_bps_best                           alamat_bps_best  score_jw
0      sefactor deos maks                         JL RAPPOCINI RAYA  0.745032
1   teras sunnah makassar                            TALASALAPANG 2  0.781769
2                     daf   JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA  0.769697
3              pp-brp kso                      JL LETJEN HERTASNING  0.691667
4                imperium                JL SKARDA N MANGASA PERMAI  0.755000
5  marala movers makassar           JL.TODDOPULI VI BORONG INDAH 10  0.749109
6         klinik addaraen               JL SULTAN ALAUDDIN NO 305 A  0.893333
7        azka prima utama  JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME  0.758269
8    dibar utama properti                            JL SYECH YUSUF  0.761870
9           berlian utama                            JL LANDAK BARU  0.856838

Contoh hasil Levenshtein:
                               input_id                          title_maps  \
0  a1b862b7-f3dd-4080-8d73-191b75975673                    simetri cafe mks
1  9f9df669-eaf0-4928-a13f-cddf4346d781         agen xamthone plus makassar
2  a1b862b7-f3dd-4080-8d73-191b75975673              daun coffee monginsidi
3  a3f39cd3-b9af-4647-a544-aeb050afa744                paprik"perfume shop"
4  a3f39cd3-b9af-4647-a544-aeb050afa744                          iye parfum
5  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f  homecare dan sunat modern makassar
6  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f                  klinik alvaro care
7  a3f39cd3-b9af-4647-a544-aeb050afa744                       aa bar parfum
8  a3f39cd3-b9af-4647-a544-aeb050afa744                   dirah shop parfum
9  a3f39cd3-b9af-4647-a544-aeb050afa744         berlian parfume jipang raya

                                        address_maps  IDSBR_best  \
0  Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...     3077001
1  JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...     2717155
2  komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...    97469495
3  Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...     5407359
4  RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...     5411746
5  Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...     4325925
6  Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...    97502853
7  Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...     5411746
8  RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...     5411746
9  Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...    97502117

                    nama_bps_best                        alamat_bps_best  \
0                     mutiara mas        JL.TIDUNG MARIOLO NO.8E, TIDUNG
1  lembaga bantuan hukum makassar  JL PELITA RAYA VI BLOK A34/9, BUAKANA
2                 daily coffe bar                             EMY SAELAN
3                     karina shop                         BTN MINASA UPA
4                     jual parfum            GRIYA FAJAR MAS BLOK M NO 2
5          marala movers makassar        JL.TODDOPULI VI BORONG INDAH 10
6                 klinik addaraen            JL SULTAN ALAUDDIN NO 305 A
7                     jual parfum            GRIYA FAJAR MAS BLOK M NO 2
8                     jual parfum            GRIYA FAJAR MAS BLOK M NO 2
9          alfa mart pinang ray a                             J L PINANG

   score_lev
0       0.44
1       0.50
2       0.36
3       0.40
4       0.64
5       0.56
6       0.61
7       0.62
8       0.47
9       0.52

### percobaan kedua(jaro-lev terpisah)

In [1]:
import pandas as pd
from rapidfuzz import process, distance

BPS_CSV  = "BPS_Rappocini_clean.csv"
MAPS_CSV = "Scraping_Rappocini_clean.csv"

OUT_JW_CSV  = "MATCHING_Rappocini_JW-ke2.csv"
OUT_LEV_CSV = "MATCHING_Rappocini_LEV-ke2.csv"

df_bps  = pd.read_csv(BPS_CSV)
df_maps = pd.read_csv(MAPS_CSV)

# Pastikan tidak ada NaN
df_bps["Nama Usaha"] = df_bps["Nama Usaha"].fillna("").astype(str)
df_maps["title"]     = df_maps["title"].fillna("").astype(str)

# List nama usaha BPS
bps_names = df_bps["Nama Usaha"].tolist()

results_jw = []
results_lev = []

# PROSES MATCHING
for _, row in df_maps.iterrows():
    query_name = row["title"]

    if query_name.strip() == "":
        continue

    # MATCHING JARO-WINKLER
    best_jw = process.extractOne(
        query_name,
        bps_names,
        scorer=distance.JaroWinkler.normalized_similarity
    )

    nama_bps_jw, score_jw, idx_jw = best_jw
    bps_row_jw = df_bps.iloc[idx_jw]

    results_jw.append({
        "input_id": row.get("input_id", ""),
        "title_maps": query_name,
        "address_maps": row.get("address", ""),

        "IDSBR_best": bps_row_jw.get("IDSBR", ""),
        "nama_bps_best": nama_bps_jw,
        "alamat_bps_best": bps_row_jw.get("Alamat", ""),

        "score_jw": round(score_jw, 2)
    })

    # MATCHING LEVENSHTEIN
    best_lev = process.extractOne(
        query_name,
        bps_names,
        scorer=distance.Levenshtein.normalized_similarity
    )

    nama_bps_lev, score_lev, idx_lev = best_lev
    bps_row_lev = df_bps.iloc[idx_lev]

    results_lev.append({
        "input_id": row.get("input_id", ""),
        "title_maps": query_name,
        "address_maps": row.get("address", ""),

        "IDSBR_best": bps_row_lev.get("IDSBR", ""),
        "nama_bps_best": nama_bps_lev,
        "alamat_bps_best": bps_row_lev.get("Alamat", ""),

        "score_lev": round(score_lev, 2)
    })

df_result_jw = pd.DataFrame(results_jw)
df_result_lev = pd.DataFrame(results_lev)

df_result_jw.to_csv(OUT_JW_CSV, index=False)
df_result_lev.to_csv(OUT_LEV_CSV, index=False)

print("Selesai!")
print("File Jaro-Winkler :", OUT_JW_CSV)
print("File Levenshtein  :", OUT_LEV_CSV)

print("\nContoh hasil Jaro-Winkler:")
print(df_result_jw.head(10))

print("\nContoh hasil Levenshtein:")
print(df_result_lev.head(10))

Selesai!
File Jaro-Winkler : MATCHING_Rappocini_JW-ke2.csv
File Levenshtein  : MATCHING_Rappocini_LEV-ke2.csv

Contoh hasil Jaro-Winkler:
                               input_id                          title_maps  \
0  a1b862b7-f3dd-4080-8d73-191b75975673                    simetri cafe mks
1  9f9df669-eaf0-4928-a13f-cddf4346d781         agen xamthone plus makassar
2  a1b862b7-f3dd-4080-8d73-191b75975673              daun coffee monginsidi
3  a3f39cd3-b9af-4647-a544-aeb050afa744                paprik"perfume shop"
4  a3f39cd3-b9af-4647-a544-aeb050afa744                          iye parfum
5  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f  homecare dan sunat modern makassar
6  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f                  klinik alvaro care
7  a3f39cd3-b9af-4647-a544-aeb050afa744                       aa bar parfum
8  a3f39cd3-b9af-4647-a544-aeb050afa744                   dirah shop parfum
9  a3f39cd3-b9af-4647-a544-aeb050afa744         berlian parfume jipang raya

                                        address_maps  IDSBR_best  \
0  Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...     4471585
1  JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...     3532554
2  komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...     3365337
3  Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...     3560125
4  RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...     4026968
5  Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...     4325925
6  Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...    97502853
7  Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...     3844982
8  RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...     3814015
9  Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...     3452839

            nama_bps_best                           alamat_bps_best  score_jw
0      sefactor deos maks                         JL RAPPOCINI RAYA      0.75
1   teras sunnah makassar                            TALASALAPANG 2      0.78
2                     daf   JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA      0.77
3              pp-brp kso                      JL LETJEN HERTASNING      0.69
4                imperium                JL SKARDA N MANGASA PERMAI      0.76
5  marala movers makassar           JL.TODDOPULI VI BORONG INDAH 10      0.75
6         klinik addaraen               JL SULTAN ALAUDDIN NO 305 A      0.89
7        azka prima utama  JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME      0.76
8    dibar utama properti                            JL SYECH YUSUF      0.76
9           berlian utama                            JL LANDAK BARU      0.86

Contoh hasil Levenshtein:
                               input_id                          title_maps  \
0  a1b862b7-f3dd-4080-8d73-191b75975673                    simetri cafe mks
1  9f9df669-eaf0-4928-a13f-cddf4346d781         agen xamthone plus makassar
2  a1b862b7-f3dd-4080-8d73-191b75975673              daun coffee monginsidi
3  a3f39cd3-b9af-4647-a544-aeb050afa744                paprik"perfume shop"
4  a3f39cd3-b9af-4647-a544-aeb050afa744                          iye parfum
5  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f  homecare dan sunat modern makassar
6  97432aae-4bc6-4f76-9a6f-4ed0e625ba8f                  klinik alvaro care
7  a3f39cd3-b9af-4647-a544-aeb050afa744                       aa bar parfum
8  a3f39cd3-b9af-4647-a544-aeb050afa744                   dirah shop parfum
9  a3f39cd3-b9af-4647-a544-aeb050afa744         berlian parfume jipang raya

                                        address_maps  IDSBR_best  \
0  Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...     3077001
1  JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...     2717155
2  komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...    97469495
3  Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...     5407359
4  RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...     5411746
5  Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...     4325925
6  Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...    97502853
7  Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...     5411746
8  RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...     5411746
9  Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...    97502117

                    nama_bps_best                        alamat_bps_best  \
0                     mutiara mas        JL.TIDUNG MARIOLO NO.8E, TIDUNG
1  lembaga bantuan hukum makassar  JL PELITA RAYA VI BLOK A34/9, BUAKANA
2                 daily coffe bar                             EMY SAELAN
3                     karina shop                         BTN MINASA UPA
4                     jual parfum            GRIYA FAJAR MAS BLOK M NO 2
5          marala movers makassar        JL.TODDOPULI VI BORONG INDAH 10
6                 klinik addaraen            JL SULTAN ALAUDDIN NO 305 A
7                     jual parfum            GRIYA FAJAR MAS BLOK M NO 2
8                     jual parfum            GRIYA FAJAR MAS BLOK M NO 2
9          alfa mart pinang ray a                             J L PINANG

   score_lev
0       0.44
1       0.50
2       0.36
3       0.40
4       0.64
5       0.56
6       0.61
7       0.62
8       0.47
9       0.52

### agar 1.0 berubah jadi 1 dan 0.9 menjadi 0.90 -tidak jadi digunakan

In [9]:
import pandas as pd
from rapidfuzz import process, distance

pd.options.display.float_format = "{:.2f}".format

BPS_CSV  = "BPS_Rappocini_clean.csv"
MAPS_CSV = "Scraping_Rappocini_clean.csv"

OUT_JW_CSV  = "MATCHING_Rappocini_JW-ke3.csv"
OUT_LEV_CSV = "MATCHING_Rappocini_LEV-ke3.csv"

df_bps  = pd.read_csv(BPS_CSV)
df_maps = pd.read_csv(MAPS_CSV)

# Pastikan tidak ada NaN
df_bps["Nama Usaha"] = df_bps["Nama Usaha"].fillna("").astype(str)
df_maps["title"]     = df_maps["title"].fillna("").astype(str)

# List nama usaha BPS
bps_names = df_bps["Nama Usaha"].tolist()

results_jw = []
results_lev = []

# PROSES MATCHING
for _, row in df_maps.iterrows():
    query_name = row["title"]

    if query_name.strip() == "":
        continue

    # MATCHING JARO-WINKLER
    best_jw = process.extractOne(
        query_name,
        bps_names,
        scorer=distance.JaroWinkler.normalized_similarity
    )

    nama_bps_jw, score_jw, idx_jw = best_jw
    bps_row_jw = df_bps.iloc[idx_jw]

    results_jw.append({
        "input_id": row.get("input_id", ""),
        "title_maps": query_name,
        "address_maps": row.get("address", ""),

        "IDSBR_best": bps_row_jw.get("IDSBR", ""),
        "nama_bps_best": nama_bps_jw,
        "alamat_bps_best": bps_row_jw.get("Alamat", ""),

        "score_jw": round(score_jw, 2)
    })

    # MATCHING LEVENSHTEIN
    best_lev = process.extractOne(
        query_name,
        bps_names,
        scorer=distance.Levenshtein.normalized_similarity
    )

    nama_bps_lev, score_lev, idx_lev = best_lev
    bps_row_lev = df_bps.iloc[idx_lev]

    results_lev.append({
        "input_id": row.get("input_id", ""),
        "title_maps": query_name,
        "address_maps": row.get("address", ""),

        "IDSBR_best": bps_row_lev.get("IDSBR", ""),
        "nama_bps_best": nama_bps_lev,
        "alamat_bps_best": bps_row_lev.get("Alamat", ""),

        "score_lev": round(score_lev, 2)
    })

df_result_jw = pd.DataFrame(results_jw)
df_result_lev = pd.DataFrame(results_lev)

df_result_jw.to_csv(OUT_JW_CSV, index=False, float_format="%.2f")
df_result_lev.to_csv(OUT_LEV_CSV, index=False, float_format="%.2f")

print("Selesai!!!!")
print("File Jaro-Winkler :", OUT_JW_CSV)
print("File Levenshtein  :", OUT_LEV_CSV)

Selesai!!!!
File Jaro-Winkler : MATCHING_Rappocini_JW-ke3.csv
File Levenshtein  : MATCHING_Rappocini_LEV-ke3.csv

In [10]:
print("\nContoh hasil Jaro-Winkler:",len(df_result_jw))
(df_result_jw.head(10))

Contoh hasil Jaro-Winkler: 7158

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.75
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.89
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",3844982,azka prima utama,JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME,0.76
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",3814015,dibar utama properti,JL SYECH YUSUF,0.76
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",3452839,berlian utama,JL LANDAK BARU,0.86

In [11]:
print("\nContoh hasil Levenshtein:",len(df_result_lev))
(df_result_lev.head(10))

Contoh hasil Levenshtein: 7158

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",0.44
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",0.50
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,0.36
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",5407359,karina shop,BTN MINASA UPA,0.40
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.64
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.56
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.61
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.62
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.47
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",97502117,alfa mart pinang ray a,J L PINANG,0.52