### PART 2

In [1]:
import pandas as pd

# Baca file Excel
df = pd.read_excel("SudahLabel-Tipa.xlsx")

# Simpan jadi CSV
df.to_csv("SudahLabel-Tipa.csv", index=False, encoding='utf-8-sig')

In [2]:
df

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,75,39,NaN
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,78,44,NaN
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,77,14,NaN
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,69,25,NaN
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,76,5,NaN
...,...,...,...,...,...,...,...,...,...
7153,0f54185c-fe91-4548-8004-812f626fbbf7,travel umroh terbaik di makassar | mamduh wisa...,"Jl. Tidung Mariolo No.2e, Bonto Makkio, Kec. R...",97489045,travel am utama,BTN MINAM UM BLOK ABHNO 8,83,26,NaN
7154,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,callme home care (layanan perawatan kesehatan ...,RCJM+MJ6 Callme Home Care (Layanan Perawatan K...,4003393,lembaga keterampilan dan pelatihan arhy's faja...,JL TALASALAPANG KOMP BTN MINASA UPA BLOK,72,27,NaN
7155,0b7f6193-a926-4d00-9e57-8b175534cc04,rallyemoto indonesia,"Jl. Pelita 2 Lrg 4 No.75, Bua Kana, Rappocini,...",3416360,raconvec indonesia,KOMP ANGING MAMIRI RESIDENCE MAKASSAR BLOK,82,6,NaN
7156,a1b862b7-f3dd-4080-8d73-191b75975673,jajini co brewing space,"Jl. Monginsidi Baru Blk No.15, RT.004/RW.02, B...",4370628,nviro global sciences,JL SYECH YUSUF LR 3,69,17,NaN
7157,bc7cdc0e-9015-4363-80a8-8a560ec6e572,hi.fashionlab cabang hilab school | butik baju...,"Jl. Aroeppala No.26, Gn. Sari, Kec. Rappocini,...",3778350,faa,"JL HERTASNING VII NO 22C RT.006 RW.003, TIDUNG",68,5,NaN

In [9]:
df = df.rename(columns={'label ': 'label'})

In [10]:
df['label'] = (
    df['label']
    .replace(r'^\s*$', 'X', regex=True)  # isi yang kosong / hanya spasi
    .fillna('X')                         # isi NaN
)

In [11]:
df['score_jw']  = df['score_jw'] / 100
df['score_lev'] = df['score_lev'] / 100

In [12]:
df

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,0.39,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,0.44,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,0.14,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,0.25,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,0.05,X
...,...,...,...,...,...,...,...,...,...
7153,0f54185c-fe91-4548-8004-812f626fbbf7,travel umroh terbaik di makassar | mamduh wisa...,"Jl. Tidung Mariolo No.2e, Bonto Makkio, Kec. R...",97489045,travel am utama,BTN MINAM UM BLOK ABHNO 8,0.83,0.26,X
7154,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,callme home care (layanan perawatan kesehatan ...,RCJM+MJ6 Callme Home Care (Layanan Perawatan K...,4003393,lembaga keterampilan dan pelatihan arhy's faja...,JL TALASALAPANG KOMP BTN MINASA UPA BLOK,0.72,0.27,X
7155,0b7f6193-a926-4d00-9e57-8b175534cc04,rallyemoto indonesia,"Jl. Pelita 2 Lrg 4 No.75, Bua Kana, Rappocini,...",3416360,raconvec indonesia,KOMP ANGING MAMIRI RESIDENCE MAKASSAR BLOK,0.82,0.06,X
7156,a1b862b7-f3dd-4080-8d73-191b75975673,jajini co brewing space,"Jl. Monginsidi Baru Blk No.15, RT.004/RW.02, B...",4370628,nviro global sciences,JL SYECH YUSUF LR 3,0.69,0.17,X
7157,bc7cdc0e-9015-4363-80a8-8a560ec6e572,hi.fashionlab cabang hilab school | butik baju...,"Jl. Aroeppala No.26, Gn. Sari, Kec. Rappocini,...",3778350,faa,"JL HERTASNING VII NO 22C RT.006 RW.003, TIDUNG",0.68,0.05,X

In [13]:
df.to_csv("SudahLabel-Tipa.csv", index=False)

### DATA DARI ORANG LAIN-linda

In [1]:
import pandas as pd

df = pd.read_excel("SudahLabel-Linda.xlsx")

df.to_csv("SudahLabel-Linda.csv", index=False, encoding='utf-8-sig')

In [2]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv("SudahLabel-Linda.csv")

print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7158

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,75,39,NaN
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,78,44,NaN
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,77,14,NaN
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,69,25,NaN
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,76,5,NaN
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,75,56,NaN
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,89,61,NaN
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",3844982,azka prima utama,JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME,76,31,NaN
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",3814015,dibar utama properti,JL SYECH YUSUF,76,3,NaN
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",3452839,berlian utama,JL LANDAK BARU,86,41,NaN

In [3]:
df['label'] = (
    df['label']
    .replace(r'^\s*$', 'X', regex=True)  # isi yang kosong / hanya spasi
    .fillna('X')                         # isi NaN
)

In [4]:
df

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,75,39,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,78,44,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,77,14,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,69,25,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,76,5,X
...,...,...,...,...,...,...,...,...,...
7153,0f54185c-fe91-4548-8004-812f626fbbf7,travel umroh terbaik di makassar | mamduh wisa...,"Jl. Tidung Mariolo No.2e, Bonto Makkio, Kec. R...",97489045,travel am utama,BTN MINAM UM BLOK ABHNO 8,83,26,X
7154,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,callme home care (layanan perawatan kesehatan ...,RCJM+MJ6 Callme Home Care (Layanan Perawatan K...,4003393,lembaga keterampilan dan pelatihan arhy's faja...,JL TALASALAPANG KOMP BTN MINASA UPA BLOK,72,27,X
7155,0b7f6193-a926-4d00-9e57-8b175534cc04,rallyemoto indonesia,"Jl. Pelita 2 Lrg 4 No.75, Bua Kana, Rappocini,...",3416360,raconvec indonesia,KOMP ANGING MAMIRI RESIDENCE MAKASSAR BLOK,82,6,X
7156,a1b862b7-f3dd-4080-8d73-191b75975673,jajini co brewing space,"Jl. Monginsidi Baru Blk No.15, RT.004/RW.02, B...",4370628,nviro global sciences,JL SYECH YUSUF LR 3,69,17,X
7157,bc7cdc0e-9015-4363-80a8-8a560ec6e572,hi.fashionlab cabang hilab school | butik baju...,"Jl. Aroeppala No.26, Gn. Sari, Kec. Rappocini,...",3778350,faa,"JL HERTASNING VII NO 22C RT.006 RW.003, TIDUNG",68,5,X

In [5]:
df['score_jw']  = df['score_jw'] / 100
df['score_lev'] = df['score_lev'] / 100

In [6]:
df

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,0.39,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,0.44,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,0.14,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,0.25,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,0.05,X
...,...,...,...,...,...,...,...,...,...
7153,0f54185c-fe91-4548-8004-812f626fbbf7,travel umroh terbaik di makassar | mamduh wisa...,"Jl. Tidung Mariolo No.2e, Bonto Makkio, Kec. R...",97489045,travel am utama,BTN MINAM UM BLOK ABHNO 8,0.83,0.26,X
7154,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,callme home care (layanan perawatan kesehatan ...,RCJM+MJ6 Callme Home Care (Layanan Perawatan K...,4003393,lembaga keterampilan dan pelatihan arhy's faja...,JL TALASALAPANG KOMP BTN MINASA UPA BLOK,0.72,0.27,X
7155,0b7f6193-a926-4d00-9e57-8b175534cc04,rallyemoto indonesia,"Jl. Pelita 2 Lrg 4 No.75, Bua Kana, Rappocini,...",3416360,raconvec indonesia,KOMP ANGING MAMIRI RESIDENCE MAKASSAR BLOK,0.82,0.06,X
7156,a1b862b7-f3dd-4080-8d73-191b75975673,jajini co brewing space,"Jl. Monginsidi Baru Blk No.15, RT.004/RW.02, B...",4370628,nviro global sciences,JL SYECH YUSUF LR 3,0.69,0.17,X
7157,bc7cdc0e-9015-4363-80a8-8a560ec6e572,hi.fashionlab cabang hilab school | butik baju...,"Jl. Aroeppala No.26, Gn. Sari, Kec. Rappocini,...",3778350,faa,"JL HERTASNING VII NO 22C RT.006 RW.003, TIDUNG",0.68,0.05,X

In [7]:
df.to_csv("SudahLabel-Linda.csv", index=False)

In [5]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv("SudahLabel-Linda.csv")

print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7158

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,0.39,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,0.44,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,0.14,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,0.25,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,0.05,X
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.75,0.56,X
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.89,0.61,X
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",3844982,azka prima utama,JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME,0.76,0.31,X
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",3814015,dibar utama properti,JL SYECH YUSUF,0.76,0.03,X
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",3452839,berlian utama,JL LANDAK BARU,0.86,0.41,X

In [6]:
print(df["label"].value_counts())

label
X    7107
Y      51
Name: count, dtype: int64

In [7]:
df["label"] = df["label"].astype(str).str.strip().str.upper()
df["label"] = df["label"].replace("Y", "Z")

In [8]:
print(df["label"].value_counts())

label
X    7107
Z      51
Name: count, dtype: int64

In [9]:
df.to_csv("SudahLabel-Linda.csv", index=False)

### DATA tifa-JW2/LEV2

In [2]:
import pandas as pd

df = pd.read_excel("YangSudahDilabel(LEV).xlsx")

df.to_csv("SudahLabel-Tifa(terpisah).csv", index=False, encoding='utf-8-sig')

In [3]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv("SudahLabel-Tifa(terpisah).csv")

print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7158

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev,Column1
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",44,NaN
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",5,NaN
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,36,NaN
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",5407359,karina shop,BTN MINASA UPA,4,NaN
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,64,NaN
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,56,NaN
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,61,NaN
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,62,NaN
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,47,NaN
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",97502117,alfa mart pinang ray a,J L PINANG,52,NaN

In [4]:
df = df.rename(columns={
    'Column1': 'label'})

In [5]:
df['label'] = (
    df['label']
    .replace(r'^\s*$', 'X', regex=True)  # isi yang kosong / hanya spasi
    .fillna('X')                         # isi NaN
)

In [7]:
df['score_lev'] = df['score_lev'] / 100

In [8]:
df.to_csv("SudahLabel-Tifa(terpisahLEV).csv", index=False)

In [9]:
import pandas as pd

df = pd.read_excel("MATCHING_Rappocini_JW-ke2.xlsx")

df.to_csv("SudahLabel-Tifa(terpisahJW).csv", index=False, encoding='utf-8-sig')

In [10]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv("SudahLabel-Tifa(terpisahJW).csv")

print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7158

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,Column1
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,75,NaN
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,78,NaN
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,77,NaN
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,69,NaN
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,76,NaN
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,75,NaN
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,89,NaN
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",3844982,azka prima utama,JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME,76,NaN
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",3814015,dibar utama properti,JL SYECH YUSUF,76,NaN
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",3452839,berlian utama,JL LANDAK BARU,86,NaN

In [11]:
df = df.rename(columns={
    'Column1': 'label'})

In [12]:
df['label'] = (
    df['label']
    .replace(r'^\s*$', 'X', regex=True)  # isi yang kosong / hanya spasi
    .fillna('X')                         # isi NaN
)

In [13]:
df['score_jw'] = df['score_jw'] / 100

In [14]:
df.to_csv("SudahLabel-Tifa(terpisahJW).csv", index=False)

### DATA tifa-JWpart2/LEVpart2-TERPISAH

## JW

In [2]:
import pandas as pd

df = pd.read_excel("SudahLabel-Tifa(terpisahJW)part2.xlsx")

df.to_csv("SudahLabel-Tifa(terpisahJW)part2.csv", index=False, encoding='utf-8-sig')

In [3]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv("SudahLabel-Tifa(terpisahJW)part2.csv")

print("Jumlah data:", len(df))
df.head(5)

Jumlah data: 7155

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,Column1
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,NaN
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,NaN
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,NaN
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,NaN
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,NaN

In [4]:
df = df.rename(columns={
    'Column1': 'label'})

In [5]:
df['label'] = (
    df['label']
    .replace(r'^\s*$', 'X', regex=True)  # isi yang kosong / hanya spasi
    .fillna('X')                         # isi NaN
)

In [7]:
df.to_csv("SudahLabel-Tifa(terpisahJW)part2.csv", index=False)

In [1]:
import pandas as pd
# Membaca file CSV
df = pd.read_csv("SudahLabel-Tifa(terpisahJW)part2.csv")
print("Jumlah data:", len(df))
df.head(3)

Jumlah data: 7155

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,X

## LEV

In [2]:
import pandas as pd

df = pd.read_excel("SudahLabel-Tifa(terpisahLEV)part2.xlsx")

df.to_csv("SudahLabel-Tifa(terpisahLEV)part2.csv", index=False, encoding='utf-8-sig')

In [3]:
import pandas as pd

# Membaca file CSV
df = pd.read_csv("SudahLabel-Tifa(terpisahLEV)part2.csv")

print("Jumlah data:", len(df))
df.head(5)

Jumlah data: 7155

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev,Column1
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",0.44,NaN
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",0.05,NaN
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,0.36,NaN
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",5407359,karina shop,BTN MINASA UPA,0.04,NaN
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.64,NaN

In [4]:
df = df.rename(columns={
    'Column1': 'label'})

In [5]:
df['label'] = (
    df['label']
    .replace(r'^\s*$', 'X', regex=True)  # isi yang kosong / hanya spasi
    .fillna('X')                         # isi NaN
)

In [6]:
df.to_csv("SudahLabel-Tifa(terpisahLEV)part2.csv", index=False)

In [7]:
import pandas as pd
# Membaca file CSV
df = pd.read_csv("SudahLabel-Tifa(terpisahLEV)part2.csv")
print("Jumlah data:", len(df))
df.head(3)

Jumlah data: 7155

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",0.44,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",0.05,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,0.36,X

### persiapan data akurasi part : SudahLabel-Tifa(terpisahJW/LEV)part2(sdhdiubah)

In [13]:
import pandas as pd

df = pd.read_excel("SudahLabel-Tifa(terpisahJW)part2(sdhdiubah).xlsx")

df = df.rename(columns={ 'Column1': 'label'})

df.to_csv(
    "SudahLabel-Tifa(terpisahJW)part3.csv",
    index=False,
    float_format="%.2f"
)

In [14]:
print(
    df["score_jw"]
      .value_counts()
      .sort_index()
)

score_jw
0.57      1
0.61      1
0.63      9
0.64      8
0.65     12
0.66     34
0.67     48
0.68     95
0.69    137
0.70    179
0.71    153
0.72    148
0.73    149
0.74    219
0.75    194
0.76    231
0.77    233
0.78    294
0.79    224
0.80    231
0.81    220
0.82    270
0.83    397
0.84    413
0.85    389
0.86    376
0.87    400
0.88    362
0.89    347
0.90    298
0.91    298
0.92    227
0.93    156
0.94    133
0.95     62
0.96     37
0.97     23
0.98     23
0.99      6
1.00    117
Name: count, dtype: int64

In [15]:
df

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,X
...,...,...,...,...,...,...,...,...
7149,0f54185c-fe91-4548-8004-812f626fbbf7,travel umroh terbaik di makassar | mamduh wisa...,"Jl. Tidung Mariolo No.2e, Bonto Makkio, Kec. R...",97489045,travel am utama,BTN MINAM UM BLOK ABHNO 8,0.83,X
7150,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,callme home care (layanan perawatan kesehatan ...,RCJM+MJ6 Callme Home Care (Layanan Perawatan K...,4003393,lembaga keterampilan dan pelatihan arhy's faja...,JL TALASALAPANG KOMP BTN MINASA UPA BLOK,0.72,X
7151,0b7f6193-a926-4d00-9e57-8b175534cc04,rallyemoto indonesia,"Jl. Pelita 2 Lrg 4 No.75, Bua Kana, Rappocini,...",3416360,raconvec indonesia,KOMP ANGING MAMIRI RESIDENCE MAKASSAR BLOK,0.82,X
7152,a1b862b7-f3dd-4080-8d73-191b75975673,jajini co brewing space,"Jl. Monginsidi Baru Blk No.15, RT.004/RW.02, B...",4370628,nviro global sciences,JL SYECH YUSUF LR 3,0.69,X
7153,bc7cdc0e-9015-4363-80a8-8a560ec6e572,hi.fashionlab cabang hilab school | butik baju...,"Jl. Aroeppala No.26, Gn. Sari, Kec. Rappocini,...",3778350,faa,"JL HERTASNING VII NO 22C RT.006 RW.003, TIDUNG",0.68,X

In [3]:
import pandas as pd

df = pd.read_excel("SudahLabel-Tifa(terpisahLEV)part2(sdhdiubah).xlsx")

df.to_csv(
    "SudahLabel-Tifa(terpisahLEV)part3.csv",
    index=False,
    float_format="%.2f"
)

In [5]:
print(
    df["score_lev"]
      .value_counts()
      .sort_index()
)

score_lev
0.14      1
0.22      1
0.24      1
0.25      2
0.26      2
       ...
0.94      5
0.95      7
0.96      1
0.97      1
1.00    117
Name: count, Length: 77, dtype: int64

In [9]:
df = df.rename(columns={
    'Column1': 'label'})

In [11]:
df.to_csv(
    "SudahLabel-Tifa(terpisahLEV)part3.csv",
    index=False,
    float_format="%.2f"
)

In [12]:
df

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",0.44,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",0.50,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,0.36,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",5407359,karina shop,BTN MINASA UPA,0.40,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.64,X
...,...,...,...,...,...,...,...,...
7149,0f54185c-fe91-4548-8004-812f626fbbf7,travel umroh terbaik di makassar | mamduh wisa...,"Jl. Tidung Mariolo No.2e, Bonto Makkio, Kec. R...",97494348,travel umroh (ir h mukhlis),BTN MINASA UPA BLOK EA NO 10,0.39,X
7150,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,callme home care (layanan perawatan kesehatan ...,RCJM+MJ6 Callme Home Care (Layanan Perawatan K...,2800282,lemb kajian pengembangan olahraga&kesehatan ind,"JL MAHONI NO 133, KASSI-KASSI",0.38,X
7151,0b7f6193-a926-4d00-9e57-8b175534cc04,rallyemoto indonesia,"Jl. Pelita 2 Lrg 4 No.75, Bua Kana, Rappocini,...",3509201,marly optima indonesia,JALAN MONUMEN EMMY SAELAN KOMPLEKS GRAHA SARI ...,0.64,X
7152,a1b862b7-f3dd-4080-8d73-191b75975673,jajini co brewing space,"Jl. Monginsidi Baru Blk No.15, RT.004/RW.02, B...",3515155,batavia prosperindo finance,JL PELITA RAYA BLOK A.22,0.37,X
7153,bc7cdc0e-9015-4363-80a8-8a560ec6e572,hi.fashionlab cabang hilab school | butik baju...,"Jl. Aroeppala No.26, Gn. Sari, Kec. Rappocini,...",2796794,musyawarah guru tata boga kota makassar,"SMK NEGERI 6 MAKASSAR JL LANDAK BARU NO 132, B...",0.36,X

### mengubah X dan Z menjadi Unmatch dan Match

In [1]:
import pandas as pd

df = pd.read_csv("SudahLabel-Tifa(terpisahJW)part3.csv")
print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7154

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,X
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.75,X
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.89,X
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",3844982,azka prima utama,JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME,0.76,X
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",3814015,dibar utama properti,JL SYECH YUSUF,0.76,X
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",3452839,berlian utama,JL LANDAK BARU,0.86,X

In [6]:

df["label"] = df["label"].astype(str).str.strip().str.upper()

df["label"] = df["label"].replace({
    "X": "unmatch",
    "Z": "match"
})

df["label"] = df["label"].str.lower()

df.to_csv("SudahLabel-Tifa(terpisahJW)part33.csv", index=False)

print("File berhasil disimpan.")

File berhasil disimpan.

In [7]:
print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7154

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_jw,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",4471585,sefactor deos maks,JL RAPPOCINI RAYA,0.75,unmatch
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",3532554,teras sunnah makassar,TALASALAPANG 2,0.78,unmatch
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",3365337,daf,JL MON.EMMY SAELAN KOMP MONUMEN MUTIARA,0.77,unmatch
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",3560125,pp-brp kso,JL LETJEN HERTASNING,0.69,unmatch
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",4026968,imperium,JL SKARDA N MANGASA PERMAI,0.76,unmatch
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.75,unmatch
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.89,unmatch
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",3844982,azka prima utama,JL SULTAN ALAUDDIN PERUMAHAN GALOSI HOME,0.76,unmatch
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",3814015,dibar utama properti,JL SYECH YUSUF,0.76,unmatch
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",3452839,berlian utama,JL LANDAK BARU,0.86,unmatch

In [8]:
import pandas as pd

df = pd.read_csv("SudahLabel-Tifa(terpisahLEV)part3.csv")
print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7154

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",0.44,X
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",0.50,X
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,0.36,X
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",5407359,karina shop,BTN MINASA UPA,0.40,X
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.64,X
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.56,X
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.61,X
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.62,X
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.47,X
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",97502117,alfa mart pinang ray a,J L PINANG,0.52,X

In [9]:
df["label"] = df["label"].astype(str).str.strip().str.upper()

df["label"] = df["label"].replace({
    "X": "unmatch",
    "Z": "match"
})

df["label"] = df["label"].str.lower()

df.to_csv("SudahLabel-Tifa(terpisahLEV)part33.csv", index=False)

print("File berhasil disimpan.")

File berhasil disimpan.

In [10]:
print("Jumlah data:", len(df))
df.head(10)

Jumlah data: 7154

,input_id,title_maps,address_maps,IDSBR_best,nama_bps_best,alamat_bps_best,score_lev,label
0,a1b862b7-f3dd-4080-8d73-191b75975673,simetri cafe mks,"Jl. Rappocini Raya No.109A, Bua Kana, Rappocin...",3077001,mutiara mas,"JL.TIDUNG MARIOLO NO.8E, TIDUNG",0.44,unmatch
1,9f9df669-eaf0-4928-a13f-cddf4346d781,agen xamthone plus makassar,"JL. A. P. Pettarani, No. 61, Bua Kana, Kec. Ma...",2717155,lembaga bantuan hukum makassar,"JL PELITA RAYA VI BLOK A34/9, BUAKANA",0.50,unmatch
2,a1b862b7-f3dd-4080-8d73-191b75975673,daun coffee monginsidi,"komp. Ruko Puri Mutiara, Jl. Monginsidi Baru N...",97469495,daily coffe bar,EMY SAELAN,0.36,unmatch
3,a3f39cd3-b9af-4647-a544-aeb050afa744,"paprik""perfume shop""","Jl. Tamalate IV No.138, Kassi-Kassi, Rappocini...",5407359,karina shop,BTN MINASA UPA,0.40,unmatch
4,a3f39cd3-b9af-4647-a544-aeb050afa744,iye parfum,"RCJW+GHR Iye Parfum, Jl. Bonto Daeng Ngirate, ...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.64,unmatch
5,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,homecare dan sunat modern makassar,"Jl. Monumen Emmy Saelan Lrg. 7, Bonto Makkio, ...",4325925,marala movers makassar,JL.TODDOPULI VI BORONG INDAH 10,0.56,unmatch
6,97432aae-4bc6-4f76-9a6f-4ed0e625ba8f,klinik alvaro care,"Blok 20, Jl. Bonto Daeng Ngirate Stp. 3 No.25,...",97502853,klinik addaraen,JL SULTAN ALAUDDIN NO 305 A,0.61,unmatch
7,a3f39cd3-b9af-4647-a544-aeb050afa744,aa bar parfum,"Jl. Toddopuli Raya No.14, Kassi-Kassi, Kec. Ra...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.62,unmatch
8,a3f39cd3-b9af-4647-a544-aeb050afa744,dirah shop parfum,"RCFP+6XG Dirah Shop Parfum, Jalan Sultan Alaud...",5411746,jual parfum,GRIYA FAJAR MAS BLOK M NO 2,0.47,unmatch
9,a3f39cd3-b9af-4647-a544-aeb050afa744,berlian parfume jipang raya,"Jl. Jipang Raya No.67, Karunrung, Kec. Rappoci...",97502117,alfa mart pinang ray a,J L PINANG,0.52,unmatch

### yang FIX untuk upload github

In [12]:
df = pd.read_csv("SudahLabel-Tifa(terpisahJW)part33.csv")

df["label"] = df["label"].astype(str).str.strip().str.upper()

df["label"] = df["label"].replace({
    "X": "unmatch",
    "Z": "match"
})

df["label"] = df["label"].str.lower()

df.to_csv("SudahLabel-(terpisahJW)partFIX.csv", index=False)

print("File berhasil disimpan.")

File berhasil disimpan.

In [13]:
df = pd.read_csv("SudahLabel-Tifa(terpisahLEV)part33.csv")

df["label"] = df["label"].astype(str).str.strip().str.upper()

df["label"] = df["label"].replace({
    "X": "unmatch",
    "Z": "match"
})

df["label"] = df["label"].str.lower()

df.to_csv("SudahLabel-(terpisahLEV)partFIX.csv", index=False)

print("File berhasil disimpan.")

File berhasil disimpan.